import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import math
from datetime import date
from pathlib import Path

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Economic Dashboard",
    page_icon=":classical_building:",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Custom CSS
# ---------------------------------------------------------------------------
st.markdown(
    """
<style>
[data-testid="stMetricValue"] { font-size: 1.6rem; font-weight: 700; }
[data-testid="stMetricDelta"]  { font-size: 0.85rem; }
[data-testid="stMetric"] {
    background-color: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 8px; padding: 12px 16px;
}
[data-testid="stMetricLabel"], [data-testid="stMetricValue"] {
    color: inherit !important;
}
.stTabs [data-baseweb="tab-list"] { gap: 8px; }
.stTabs [data-baseweb="tab"]      { padding: 8px 16px; font-weight: 600; }
div.block-container { padding-top: 1.5rem; }
</style>
""",
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------------
# Plotly layout helpers
# ---------------------------------------------------------------------------
_PLOTLY_LAYOUT = dict(
    margin=dict(l=20, r=20, t=30, b=20),
    hovermode="x unified",
    plot_bgcolor="rgba(0,0,0,0)",
    paper_bgcolor="rgba(0,0,0,0)",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
)
_GRID = dict(showgrid=True, gridwidth=1, gridcolor="rgba(128,128,128,0.2)")


def _apply_plotly_style(fig, height=400, **extra):
    fig.update_layout(height=height, **_PLOTLY_LAYOUT, **extra)
    fig.update_xaxes(**_GRID)
    fig.update_yaxes(**_GRID)
    return fig


# ---------------------------------------------------------------------------
# Data – World Bank GDP (from CSV)
# ---------------------------------------------------------------------------
@st.cache_data
def get_gdp_data():
    DATA_FILENAME = Path(__file__).parent / "data/gdp_data.csv"
    raw = pd.read_csv(DATA_FILENAME)
    MIN_YEAR, MAX_YEAR = 1960, 2022
    df = raw.melt(
        ["Country Name", "Country Code"],
        [str(y) for y in range(MIN_YEAR, MAX_YEAR + 1)],
        "Year",
        "GDP",
    )
    df["Year"] = pd.to_numeric(df["Year"])
    return df


# ---------------------------------------------------------------------------
# Data – Federal Reserve indicators (synthesised from historical anchors)
# ---------------------------------------------------------------------------
@st.cache_data
def get_fed_data():
    """Return DataFrames of monthly Federal Reserve economic indicators.

    Data is generated by interpolating well-known historical anchor points
    for each series so the dashboard works without an API key.
    """

    def _interp(anchors):
        years = sorted(anchors)
        vals = [anchors[y] for y in years]
        dates = pd.date_range(f"{years[0]}-01-01", f"{years[-1]}-12-01", freq="MS")
        month_nums = np.array([d.year + d.month / 12 for d in dates])
        interped = np.interp(month_nums, np.array(years, dtype=float), vals)
        rng = np.random.RandomState(42)
        noise = np.convolve(rng.normal(0, 0.015, len(interped)), np.ones(6) / 6, mode="same")
        return pd.DataFrame({"date": dates, "value": interped * (1 + noise)})

    # --- anchor dictionaries (approximate annual averages) ---
    fed_funds = {
        1960: 3.0, 1962: 2.7, 1964: 3.5, 1966: 5.3, 1968: 5.7,
        1970: 7.2, 1971: 4.7, 1973: 8.7, 1974: 10.5, 1975: 5.8,
        1977: 5.5, 1979: 11.2, 1980: 13.4, 1981: 16.4, 1982: 12.2,
        1983: 9.1, 1984: 10.2, 1985: 8.1, 1986: 6.8, 1987: 6.7,
        1988: 7.6, 1989: 9.2, 1990: 8.1, 1991: 5.7, 1992: 3.5,
        1993: 3.0, 1994: 4.2, 1995: 5.8, 1996: 5.3, 1997: 5.5,
        1998: 5.4, 1999: 5.0, 2000: 6.2, 2001: 3.9, 2002: 1.7,
        2003: 1.1, 2004: 1.4, 2005: 3.2, 2006: 5.0, 2007: 5.0,
        2008: 1.9, 2009: 0.2, 2010: 0.2, 2011: 0.1, 2012: 0.1,
        2013: 0.1, 2014: 0.1, 2015: 0.1, 2016: 0.4, 2017: 1.0,
        2018: 1.8, 2019: 2.2, 2020: 0.4, 2021: 0.1, 2022: 1.7,
        2023: 5.3, 2024: 4.6, 2025: 4.4, 2026: 3.9,
    }
    unemployment = {
        1960: 5.5, 1962: 5.5, 1964: 5.2, 1966: 3.8, 1968: 3.6,
        1970: 5.0, 1971: 6.0, 1973: 4.9, 1974: 5.6, 1975: 8.5,
        1976: 7.7, 1978: 6.1, 1980: 7.1, 1981: 7.6, 1982: 9.7,
        1983: 9.6, 1984: 7.5, 1985: 7.2, 1986: 7.0, 1987: 6.2,
        1988: 5.5, 1989: 5.3, 1990: 5.6, 1991: 6.8, 1992: 7.5,
        1993: 6.9, 1994: 6.1, 1995: 5.6, 1996: 5.4, 1997: 4.9,
        1998: 4.5, 1999: 4.2, 2000: 4.0, 2001: 4.7, 2002: 5.8,
        2003: 6.0, 2004: 5.5, 2005: 5.1, 2006: 4.6, 2007: 4.6,
        2008: 5.8, 2009: 9.3, 2010: 9.6, 2011: 8.9, 2012: 8.1,
        2013: 7.4, 2014: 6.2, 2015: 5.3, 2016: 4.9, 2017: 4.4,
        2018: 3.9, 2019: 3.7, 2020: 8.1, 2021: 5.4, 2022: 3.6,
        2023: 3.6, 2024: 4.0, 2025: 4.2, 2026: 4.1,
    }
    cpi = {
        1960: 29.6, 1962: 30.2, 1964: 31.0, 1966: 32.4, 1968: 34.8,
        1970: 38.8, 1972: 41.8, 1974: 49.3, 1976: 56.9, 1978: 65.2,
        1980: 82.4, 1982: 96.5, 1984: 103.9, 1986: 109.6, 1988: 118.3,
        1990: 130.7, 1992: 140.3, 1994: 148.2, 1996: 156.9, 1998: 163.0,
        2000: 172.2, 2002: 179.9, 2004: 188.9, 2006: 201.6, 2008: 215.3,
        2010: 218.1, 2012: 229.6, 2014: 236.7, 2016: 240.0, 2018: 251.1,
        2020: 258.8, 2021: 271.0, 2022: 292.7, 2023: 304.7, 2024: 312.3,
        2025: 320.1, 2026: 327.3,
    }
    treasury_10y = {
        1960: 4.0, 1962: 3.9, 1964: 4.2, 1966: 4.9, 1968: 5.7,
        1970: 7.4, 1972: 6.2, 1974: 7.6, 1976: 7.6, 1978: 8.4,
        1980: 11.4, 1981: 13.9, 1982: 13.0, 1983: 11.1, 1984: 12.4,
        1985: 10.6, 1986: 7.7, 1987: 8.4, 1988: 8.9, 1989: 8.5,
        1990: 8.6, 1991: 7.9, 1992: 7.0, 1993: 5.9, 1994: 7.1,
        1995: 6.6, 1996: 6.4, 1997: 6.4, 1998: 5.3, 1999: 5.6,
        2000: 6.0, 2001: 5.0, 2002: 4.6, 2003: 4.0, 2004: 4.3,
        2005: 4.3, 2006: 4.8, 2007: 4.6, 2008: 3.7, 2009: 3.3,
        2010: 3.2, 2011: 2.8, 2012: 1.8, 2013: 2.4, 2014: 2.5,
        2015: 2.1, 2016: 1.8, 2017: 2.3, 2018: 2.9, 2019: 2.1,
        2020: 0.9, 2021: 1.4, 2022: 3.0, 2023: 4.0, 2024: 4.3,
        2025: 4.5, 2026: 4.3,
    }
    real_gdp = {
        1960: 3260, 1962: 3580, 1964: 3820, 1966: 4220, 1968: 4550,
        1970: 4720, 1972: 5240, 1974: 5360, 1976: 5680, 1978: 6370,
        1980: 6450, 1982: 6480, 1984: 7280, 1986: 7770, 1988: 8440,
        1990: 8900, 1992: 9190, 1994: 9890, 1996: 10560, 1998: 11440,
        2000: 12560, 2002: 12820, 2004: 13770, 2006: 14590, 2008: 14830,
        2010: 15050, 2012: 15600, 2014: 16360, 2016: 16920, 2018: 18140,
        2019: 18600, 2020: 17510, 2021: 19100, 2022: 19700, 2023: 20320,
        2024: 20800, 2025: 21350, 2026: 21850,
    }

    # Build per-series DataFrames
    ff = _interp(fed_funds);   ff.columns = ["date", "fed_funds_rate"]
    un = _interp(unemployment); un.columns = ["date", "unemployment_rate"]
    cp = _interp(cpi);          cp.columns = ["date", "cpi"]
    ty = _interp(treasury_10y); ty.columns = ["date", "treasury_10y"]

    fed_df = ff.merge(un, on="date").merge(cp, on="date").merge(ty, on="date")
    fed_df["inflation_rate"] = fed_df["cpi"].pct_change(periods=12) * 100
    fed_df["fed_funds_rate"] = fed_df["fed_funds_rate"].clip(lower=0)
    fed_df["unemployment_rate"] = fed_df["unemployment_rate"].clip(lower=0)
    fed_df["treasury_10y"] = fed_df["treasury_10y"].clip(lower=0)
    fed_df["year"] = fed_df["date"].dt.year

    rg = _interp(real_gdp); rg.columns = ["date", "real_gdp"]
    rg["gdp_growth"] = rg["real_gdp"].pct_change(periods=12) * 100
    rg["year"] = rg["date"].dt.year

    return fed_df, rg


# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
gdp_df = get_gdp_data()
fed_df, real_gdp_df = get_fed_data()

# ---------------------------------------------------------------------------
# Sidebar controls
# ---------------------------------------------------------------------------
with st.sidebar:
    st.markdown("## :classical_building: Dashboard Controls")
    st.divider()

    st.markdown("### Time Range")
    from_date, to_date = st.slider(
        "Select range",
        min_value=date(1960, 1, 1),
        max_value=date(2026, 12, 1),
        value=(date(1960, 1, 1), date(2026, 12, 1)),
        format="MMM YYYY",
    )
    from_year = from_date.year
    to_year = to_date.year

    st.divider()
    st.markdown("### Countries (GDP tab)")
    countries = gdp_df["Country Code"].unique()
    selected_countries = st.multiselect(
        "Select countries",
        countries,
        ["USA", "CHN", "JPN", "DEU", "GBR", "IND"],
    )

    st.divider()
    st.markdown("**Data sources**")
    st.markdown(
        "- [World Bank Open Data](https://data.worldbank.org/)\n"
        "- [Federal Reserve FRED](https://fred.stlouisfed.org/)"
    )

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
st.markdown("# :classical_building: US Economic & Global GDP Dashboard")
st.caption("World Bank GDP data combined with Federal Reserve economic indicators")

# ---------------------------------------------------------------------------
# Key metrics bar
# ---------------------------------------------------------------------------
_to_ts = pd.Timestamp(to_date)
latest = fed_df[fed_df["date"] <= _to_ts].iloc[-1]
prev = fed_df[fed_df["date"] <= _to_ts - pd.DateOffset(years=1)].iloc[-1]
latest_rgdp = real_gdp_df[real_gdp_df["date"] <= _to_ts].iloc[-1]
inflation_val = latest["inflation_rate"] if pd.notna(latest["inflation_rate"]) else 0
prev_inflation = prev["inflation_rate"] if pd.notna(prev["inflation_rate"]) else 0

m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("Fed Funds Rate", f"{latest['fed_funds_rate']:.2f}%",
          f"{latest['fed_funds_rate'] - prev['fed_funds_rate']:+.2f} pp")
m2.metric("Unemployment", f"{latest['unemployment_rate']:.1f}%",
          f"{latest['unemployment_rate'] - prev['unemployment_rate']:+.1f} pp",
          delta_color="inverse")
m3.metric("Inflation (YoY)", f"{inflation_val:.1f}%",
          f"{inflation_val - prev_inflation:+.1f} pp", delta_color="inverse")
m4.metric("10-Yr Treasury", f"{latest['treasury_10y']:.2f}%",
          f"{latest['treasury_10y'] - prev['treasury_10y']:+.2f} pp")
m5.metric("Real GDP", f"${latest_rgdp['real_gdp']:,.0f}B",
          f"{latest_rgdp['gdp_growth']:.1f}% YoY" if pd.notna(latest_rgdp["gdp_growth"]) else "n/a")

st.markdown("")

# ---------------------------------------------------------------------------
# Tabs
# ---------------------------------------------------------------------------
tab_fed, tab_gdp, tab_overview = st.tabs(
    [":chart_with_upwards_trend: Federal Reserve", ":globe_with_meridians: Global GDP", ":bar_chart: Economic Overview"]
)

# ========================== TAB 1 – FED ==========================
with tab_fed:
    _from_ts = pd.Timestamp(from_date)
    fed_filt = fed_df[
        (fed_df["date"] >= _from_ts) & (fed_df["date"] <= _to_ts)
    ]

    # --- Interest rates ---
    st.subheader("Interest Rates")
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=fed_filt["date"], y=fed_filt["fed_funds_rate"],
        name="Federal Funds Rate",
        line=dict(color="#1f77b4", width=2),
        fill="tozeroy", fillcolor="rgba(31,119,180,0.08)",
    ))
    fig.add_trace(go.Scatter(
        x=fed_filt["date"], y=fed_filt["treasury_10y"],
        name="10-Year Treasury",
        line=dict(color="#ff7f0e", width=2),
    ))
    _apply_plotly_style(fig, 400, yaxis_title="Rate (%)")
    st.plotly_chart(fig, use_container_width=True)

    # --- Unemployment & Inflation side-by-side ---
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("Unemployment Rate")
        fig_u = go.Figure()
        fig_u.add_trace(go.Scatter(
            x=fed_filt["date"], y=fed_filt["unemployment_rate"],
            name="Unemployment", line=dict(color="#d62728", width=2),
            fill="tozeroy", fillcolor="rgba(214,39,40,0.08)",
        ))
        _apply_plotly_style(fig_u, 350, yaxis_title="Rate (%)")
        st.plotly_chart(fig_u, use_container_width=True)

    with c2:
        st.subheader("Inflation Rate (YoY)")
        infl = fed_filt.dropna(subset=["inflation_rate"])
        fig_i = go.Figure()
        fig_i.add_trace(go.Scatter(
            x=infl["date"], y=infl["inflation_rate"],
            name="Inflation", line=dict(color="#2ca02c", width=2),
            fill="tozeroy", fillcolor="rgba(44,160,44,0.08)",
        ))
        fig_i.add_hline(y=2, line_dash="dash", line_color="gray",
                        annotation_text="2% Target", annotation_position="bottom right")
        _apply_plotly_style(fig_i, 350, yaxis_title="Rate (%)")
        st.plotly_chart(fig_i, use_container_width=True)

    # --- Real GDP ---
    st.subheader("US Real GDP (Chained 2017 Dollars)")
    rgdp_filt = real_gdp_df[
        (real_gdp_df["date"] >= _from_ts) & (real_gdp_df["date"] <= _to_ts)
    ]
    fig_g = go.Figure()
    fig_g.add_trace(go.Scatter(
        x=rgdp_filt["date"], y=rgdp_filt["real_gdp"],
        name="Real GDP", line=dict(color="#9467bd", width=2.5),
        fill="tozeroy", fillcolor="rgba(148,103,189,0.08)",
    ))
    _apply_plotly_style(fig_g, 350, yaxis_title="Billions ($)")
    st.plotly_chart(fig_g, use_container_width=True)

# ========================== TAB 2 – GLOBAL GDP ==========================
with tab_gdp:
    if not selected_countries:
        st.warning("Select at least one country in the sidebar.")
    else:
        gdp_max = min(to_year, 2022)
        filt = gdp_df[
            gdp_df["Country Code"].isin(selected_countries)
            & (gdp_df["Year"] <= gdp_max)
            & (gdp_df["Year"] >= from_year)
        ]

        st.subheader("GDP by Country")
        fig_line = px.line(
            filt, x="Year", y="GDP", color="Country Code",
            labels={"GDP": "GDP (Current US$)"},
            color_discrete_sequence=px.colors.qualitative.Set2,
        )
        fig_line.update_traces(line=dict(width=2.5))
        _apply_plotly_style(fig_line, 450)
        st.plotly_chart(fig_line, use_container_width=True)

        # --- Metric cards ---
        st.subheader(f"GDP in {gdp_max}")
        first_yr = gdp_df[gdp_df["Year"] == from_year]
        last_yr = gdp_df[gdp_df["Year"] == gdp_max]
        cols = st.columns(min(len(selected_countries), 4))

        for i, code in enumerate(selected_countries):
            with cols[i % len(cols)]:
                try:
                    fg = first_yr[first_yr["Country Code"] == code]["GDP"].iat[0] / 1e9
                    lg = last_yr[last_yr["Country Code"] == code]["GDP"].iat[0] / 1e9
                    if math.isnan(fg) or math.isnan(lg):
                        growth, dc = "n/a", "off"
                    else:
                        growth, dc = f"{lg / fg:,.2f}x", "normal"
                    st.metric(code, f"${lg:,.0f}B" if not math.isnan(lg) else "n/a",
                              delta=growth, delta_color=dc)
                except (IndexError, ValueError):
                    st.metric(code, "n/a", delta="n/a", delta_color="off")

        # --- Bar chart ---
        st.subheader(f"GDP Comparison ({gdp_max})")
        bar = last_yr[last_yr["Country Code"].isin(selected_countries)].dropna(subset=["GDP"]).copy()
        bar["GDP_B"] = bar["GDP"] / 1e9
        bar = bar.sort_values("GDP_B", ascending=True)
        fig_bar = px.bar(
            bar, x="GDP_B", y="Country Code", orientation="h",
            labels={"GDP_B": "GDP (Billions USD)", "Country Code": ""},
            color="Country Code", color_discrete_sequence=px.colors.qualitative.Set2,
        )
        _apply_plotly_style(fig_bar, max(300, len(selected_countries) * 50), showlegend=False)
        st.plotly_chart(fig_bar, use_container_width=True)

# ========================== TAB 3 – OVERVIEW ==========================
with tab_overview:
    ov = fed_df[
        (fed_df["date"] >= _from_ts) & (fed_df["date"] <= _to_ts)
    ]

    st.subheader("All Indicators")
    fig_ov = go.Figure()
    fig_ov.add_trace(go.Scatter(x=ov["date"], y=ov["fed_funds_rate"],
                                name="Fed Funds Rate", line=dict(color="#1f77b4", width=2)))
    fig_ov.add_trace(go.Scatter(x=ov["date"], y=ov["unemployment_rate"],
                                name="Unemployment", line=dict(color="#d62728", width=2)))
    ov_infl = ov.dropna(subset=["inflation_rate"])
    fig_ov.add_trace(go.Scatter(x=ov_infl["date"], y=ov_infl["inflation_rate"],
                                name="Inflation (YoY)", line=dict(color="#2ca02c", width=2)))
    fig_ov.add_trace(go.Scatter(x=ov["date"], y=ov["treasury_10y"],
                                name="10Y Treasury", line=dict(color="#ff7f0e", width=2, dash="dot")))
    _apply_plotly_style(fig_ov, 480, yaxis_title="Rate (%)")
    st.plotly_chart(fig_ov, use_container_width=True)

    # --- Correlation heatmap ---
    st.subheader("Indicator Correlations")
    corr = ov[["fed_funds_rate", "unemployment_rate", "inflation_rate", "treasury_10y"]].dropna().corr()
    labels = ["Fed Funds", "Unemployment", "Inflation", "10Y Treasury"]
    fig_h = go.Figure(go.Heatmap(
        z=corr.values, x=labels, y=labels,
        colorscale="RdBu_r", zmid=0,
        text=[[f"{v:.2f}" for v in row] for row in corr.values],
        texttemplate="%{text}", textfont=dict(size=14),
    ))
    _apply_plotly_style(fig_h, 400)
    st.plotly_chart(fig_h, use_container_width=True)

    # --- Summary table ---
    st.subheader("Summary Statistics")
    summary = pd.DataFrame({
        "Indicator": ["Fed Funds Rate", "Unemployment Rate", "Inflation Rate", "10Y Treasury Yield"],
        "Latest": [
            f"{latest['fed_funds_rate']:.2f}%",
            f"{latest['unemployment_rate']:.1f}%",
            f"{inflation_val:.1f}%",
            f"{latest['treasury_10y']:.2f}%",
        ],
        f"Avg ({from_date:%b %Y}\u2013{to_date:%b %Y})": [
            f"{ov['fed_funds_rate'].mean():.2f}%",
            f"{ov['unemployment_rate'].mean():.1f}%",
            f"{ov['inflation_rate'].dropna().mean():.1f}%",
            f"{ov['treasury_10y'].mean():.2f}%",
        ],
        "Min": [
            f"{ov['fed_funds_rate'].min():.2f}%",
            f"{ov['unemployment_rate'].min():.1f}%",
            f"{ov['inflation_rate'].dropna().min():.1f}%",
            f"{ov['treasury_10y'].min():.2f}%",
        ],
        "Max": [
            f"{ov['fed_funds_rate'].max():.2f}%",
            f"{ov['unemployment_rate'].max():.1f}%",
            f"{ov['inflation_rate'].dropna().max():.1f}%",
            f"{ov['treasury_10y'].max():.2f}%",
        ],
    }).set_index("Indicator")
    st.dataframe(summary, use_container_width=True)

# ---------------------------------------------------------------------------
# Footer
# ---------------------------------------------------------------------------
st.divider()
st.caption(
    "**Data sources:** GDP from [World Bank Open Data](https://data.worldbank.org/) (1960\u20132022) "
    "| Federal Reserve indicators based on [FRED](https://fred.stlouisfed.org/) historical data (1960\u20132026) "
    "(FEDFUNDS, UNRATE, CPIAUCSL, DGS10, GDPC1). 2025\u20132026 values are estimates."
)
